const User = require("../models/userModel");
 // Assuming you have a User model
const Bill = require("../models/billModel"); 
// exports.getUsers = async (req, res, next) => {
//   try {
//     const users = await User.find({});
//     res.status(200).json({ users });
//   } catch (err) {
//     res.status(500).json({ error: err.message });
//   }
// };

exports.getUsers = async (req, res) => {
  try {
    const { region, name } = req.query;
    const query = {};

    if (region) query.region = region;
    if (name) query.name = new RegExp(name, "i"); // Case-insensitive search

    const users = await User.find(query);
    res.status(200).json({ users });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

exports.getUser = async (req, res, next) => {
  try {
    const user = await User.findById(req.params.id); // Assuming you're using MongoDB and Mongoose
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }
    res.json({ user });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Server error" });
  }
};

// exports.createUser = async (req, res) => {
//   console.log("Entering createUser handler...");
//   try {
//     const user = new User(req.body);
//     console.log("User data received:", req.body);
//     await user.save();
//     console.log("User saved successfully!");
//     res.status(200).json({ message: "User created successfully!", user });
//   } catch (err) {
//     console.error("Error saving user:", err);

//     // Handle duplicate key error (e.g., unique constraint on fields like email)
//     if (err.code === 11000) {
//       const field = Object.keys(err.keyValue)[0]; // Get the field causing the duplicate
//       res.status(400).json({
//         // error: `Duplicate value for field: ${field}. Please use a unique value.`
//         error: `This ${field} already exists. Please enter diffrent value!`
//       });
//     }
//     // Handle validation errors
//     else if (err.name === "ValidationError") {
//       const errors = Object.values(err.errors).map((e) => e.message);
//       res.status(400).json({ error: "Validation error", details: errors });
//     }
//     // Handle other errors
//     else {
//       res
//         .status(500)
//         .json({ error: "Internal server error", details: err.message });
//     }
//   }
// };

exports.createUser = async (req, res) => {
  try {
    const { name, email, phone, address, region, password } = req.body;

    if (!region || !["North", "South", "East", "West"].includes(region)) {
      return res.status(400).json({ error: "Invalid or missing region." });
    }

    const user = new User({ name, email, phone, address, region, password });
    await user.save();

    res.status(201).json({ message: "User created successfully!", user });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

exports.editUser = async (req, res) => {
  try {
    const user = await User.findByIdAndUpdate(req.params.id, req.body, {
      new: true,
    });
    if (!user) return res.status(404).json({ message: "User not found!" });
    res.json({ message: "User updated successfully!", user });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

exports.deleteUser = async (req, res) => {
  try {
    const user = await User.findByIdAndDelete(req.params.id);
    if (!user) return res.status(404).json({ message: "User not found!" });
    res.json({ message: "User deleted successfully!" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

exports.getRegion = async (req, res) => {
  try {
    const regions = await region.find(); // Adjust based on your database structure
    res.status(200).json({ regions });
  } catch (error) {
    res.status(500).json({ message: "Error fetching regions" });
  }
};


// Assuming you have a Bill model

exports.getAdminDashboardData = async (req, res) => {
  try {
    // Get total users count
    const totalUsers = await User.countDocuments();

    // Get total units consumed by all users
    const totalUnits = await Bill.aggregate([
      { $group: { _id: null, totalUnits: { $sum: "$unitsUsed" } } }
    ]);

    // Get total fare generated by all users
    const totalFare = await Bill.aggregate([
      { $group: { _id: null, totalFare: { $sum: "$amount" } } }
    ]);

    // Get total payable amount (pending bills)
    const totalPending = await Bill.aggregate([
      { $match: { status: "Pending" } },
      { $group: { _id: null, totalPending: { $sum: "$amount" } } }
    ]);

    const totalPendingBills = await Bill.aggregate([
      { $match: { status: "Pending" } }
     
    ]);

    // Get total number of paid bills and the total amount received from paid bills
    const paidBills = await Bill.aggregate([
      { $match: { status: "Paid" } },
      { $group: { _id: null, paidCount: { $sum: 1 }, totalPaidAmount: { $sum: "$amount" } } }
    ]);

    // Send the aggregated data as response
    res.status(200).json({
      totalUsers,
      totalUnits: totalUnits[0]?.totalUnits || 0,
      totalFare: totalFare[0]?.totalFare || 0,
      totalPending: totalPending[0]?.totalPending || 0,
      paidBillsCount: paidBills[0]?.paidCount || 0,
      totalPaidAmount: paidBills[0]?.totalPaidAmount || 0,
      totalPendingBills: totalPendingBills.length || 0,
      totalBills: await Bill.countDocuments() || 0,
      averageBillAmount: await Bill.aggregate([
        { $group: { _id: null, averageBillAmount: { $avg: "$amount" } } }
      ])[0]?.averageBillAmount || 0,
    });
  } catch (err) {
    console.error("Error fetching admin dashboard data:", err);
    res.status(500).json({ error: err.message });
  }
};

